title: "Cyber Blog"
description: "Blog de ciberseguridad desplegado automáticamente con GitHub Pages (Actions)."
brand: "CYBER·LAB"
url: "https://example.github.io/cyber-blog"
permalink: /:slug/
markdown: kramdown
highlighter: rouge
timezone: Europe/Madrid
excerpt_separator: "<!--more-->"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 9
paginate_path: "/page:num/"
