title: "RAZOR — Blog"
description: "Blog de ciberseguridad desplegado automáticamente con GitHub Pages (Actions)."
brand: "RAZOR"
url: "https://example.github.io/cyber-blog"  # cámbialo en GitHub
permalink: /:slug/
markdown: kramdown
highlighter: rouge
timezone: Europe/Madrid
excerpt_separator: "<!--more-->"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10
paginate_path: "/page:num/"

exclude:
  - README.md
  - "*.zip"
